spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #(create-drop ---- create ---- update ---- none)
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
